version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: surveys
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d surveys"]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:7
    ports: ["6379:6379"]
  api:
    build: .
    environment:
      DB_URL: postgres://app:app@db:5432/surveys
      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecret
      PORT: 3000
    ports: ["3000:3000"]
    depends_on:
      db: { condition: service_healthy }
      redis:
        condition: service_started
volumes:
  dbdata:
